"""Build the site's WOFF2 fonts from the pinned official Vollkorn source.

Requires fonttools[woff]==4.64.0 and brotli==1.2.0. Run from any directory.
"""
import json
from hashlib import sha256
from io import BytesIO
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen

from fontTools import subset
from fontTools.ttLib import TTFont

REVISION = '38ab7a896bd6b163ac7f834ec696d6c68e5dedd6'
UPSTREAM = f'https://raw.githubusercontent.com/FAlthausen/Vollkorn-Typeface/{REVISION}'
OUTPUT = Path(__file__).resolve().parents[1] / 'frontend/static/fonts/vollkorn-5.000'
SOURCES = {
    'regular': ('Vollkorn[wght].ttf', 'd4d26fd39d2d41c7079d12bc06081e8262d0ed03bac16ff9083481f44faf92fa'),
    'italic': ('Vollkorn-Italic[wght].ttf', '2ba5fc8c143d65a30c6e2efee2a9938bd9baeb870af8c231281b8172752127af'),
}


def fetch(path):
    with urlopen(f'{UPSTREAM}/{quote(path)}', timeout=60) as response:
        return response.read()


def codepoints(specification):
    result = set()
    for item in specification.split(','):
        bounds = item.strip()[2:].split('-')
        result.update(range(int(bounds[0], 16), int(bounds[-1], 16) + 1))
    return result


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    definitions = json.loads(Path(__file__).with_name('vollkorn-subsets.json').read_text())
    css = ['/* Generated by scripts/build_fonts.py. See README.md and OFL.txt. */\n']
    generated = set()
    for style, (filename, checksum) in SOURCES.items():
        data = fetch(f'fonts/variable/{filename}')
        if sha256(data).hexdigest() != checksum:
            raise ValueError(f'Unexpected upstream font: {filename}')
        # Keep source interpolation: trimming it rounds glyphs at weight 600.
        languages = dict(definitions[style])
        if style == 'regular':
            latin = languages.pop('latin')
            greek = languages.pop('greek')
            languages['latin-greek'] = {
                'unicode_range': latin['unicode_range'] + ', ' + greek['unicode_range'],
                'unicodes': latin['unicodes'] + ', ' + greek['unicodes'],
            }
        for language, definition in languages.items():
            part = TTFont(BytesIO(data), recalcBBoxes=False, recalcTimestamp=False)
            options = subset.Options()
            # Glyph names affect small-text rasterization in browsers.
            options.glyph_names = True
            # Match the previous web fonts' hinting tables.
            options.drop_tables.append('prep')
            # Default shaping features preserve kerning, ligatures and marks;
            # unused optional features such as small caps are omitted.
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=codepoints(definition['unicodes']))
            subsetter.subset(part)
            part.flavor = 'woff2'
            output_name = f'vollkorn-{style}-{language}.woff2'
            part.save(OUTPUT / output_name)
            generated.add(output_name)
            css.append(f'''/* {language} */
@font-face {{
  font-family: 'Vollkorn';
  font-style: {'normal' if style == 'regular' else 'italic'};
  font-weight: 400 600;
  font-display: swap;
  src: url({output_name}) format('woff2');
  unicode-range: {definition['unicode_range']};
}}
''')
    for previous in OUTPUT.glob('*.woff2'):
        if previous.name not in generated:
            previous.unlink()
    (OUTPUT / 'fonts.css').write_text('\n'.join(css))
    for name in ['OFL.txt', 'Fontlog.txt']:
        text = fetch(name).decode('utf-8')
        normalized = '\n'.join(line.rstrip() for line in text.splitlines()).rstrip() + '\n'
        (OUTPUT / name).write_text(normalized)


if __name__ == '__main__':
    main()
