name: Deploy Bot to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'
      - '.github/workflows/deploy-bot.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: us-central1
      CLOUD_RUN_SERVICE: bot-service
      DOCKER_IMAGE_TAG: us-central1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/wittgenstein/bot-service:${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./bot
        push: true
        tags: ${{ env.DOCKER_IMAGE_TAG }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.CLOUD_RUN_SERVICE }}
        image: ${{ env.DOCKER_IMAGE_TAG }}
        region: ${{ env.REGION }}
        flags: --allow-unauthenticated
        env_vars: |
          GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}
