name: Deploy Website to Google App Engine

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to App Engine
      run: |
        cd frontend
        gcloud app deploy app.yaml --quiet
